spring:
 application:
  name: firstrestservice
 datasource:
  url: jdbc:mysql://localhost:3306/mphasisla
  username: root
  password: root@39
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa: 
  hibernate:
   ddl-auto: update
  show-sql: true
